### ISSUE TITLE
week 01 回覆

### ISSUE THREAD

**Issue by azole** [ching11720/git-practice#1]
- git 實驗觀察做得不錯，透過你自己的實驗觀察，能不能總結出 git 到底是怎麼運作的？他是怎麼儲存資料的？
- 團隊合作這件事，是需要練習的，有時候可能不要想著可以從別人那邊學習到什麼，換個角度想，你分享了，你練習輸出、你練習了有條理地表達，這些都是你的收穫，至於別人願意不願意這樣做，那是他的課題，不是你的。
- 因為還不夠認識你，所以目前也無法給你關於團隊合作好的建議，只能先提醒你，在業界工作，幾乎都是團隊合作，很少很少有人是獨立工作的，特別是在你還是 junior、你還不夠強的時候。
  - 你有沒有試著從曾經同組的同學那邊取得回饋過？例如你跟他們合作的過程當中，他們覺得 (1) 你做得好的地方、(2) 你可以做得更好的地方，分別有哪些？

**Comment by ching11720** [comment]
感謝老師的回覆！總結的部分有在git.md做一些補充，然後video裡面也有補充一些東西

**Comment by azole** [comment]
謝謝你的回覆，做得很好！

團隊合作這件事，難就是難在這是跟人有關的事，不同的團隊成員、不同的特質，每次都會不太一樣，只能見招拆招，但無論如何，把自己先做好，都是最基本的，看來你做得不錯啊，自己做得不錯的時候，就可以從「為自己規劃」跨出去到「為團隊規劃」，也就是把自己的影響力逐步擴大出去。但這比技術，更沒有標準答案了，一生的課題，但心裡能 keep in mind 要去學習這件事，就會愈來愈好的。

那如果沒有其他要再跟我討論的部分，這個 issue 就可以先 close 了。
